services:
  otel-collector:
    command: ["--config=/etc/otel-config.yaml"]
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-collector-config.yml:/etc/otel-config.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "8888:8888" # Prometheus metrics exposed by the agent
    environment:
      HOSTNAME: ${HOSTNAME:-wakabox}
    networks:
      - monitor-net
    read_only: true
    security_opt:
      - no-new-privileges:true

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - monitor-net
    read_only: true
    security_opt:
      - no-new-privileges:true

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    networks:
      - monitor-net
    read_only: true
    security_opt:
      - no-new-privileges:true

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    container_name: tempo
    restart: always
    ports:
      - "3200:3200" # tempo
        # - "4317:4317" # otlp grpc
    volumes:
      - ./tempo-config.yml:/etc/tempo.yaml
      - tempo_data:/var/tempo
    networks:
      - monitor-net
    read_only: true
    security_opt:
      - no-new-privileges:true

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    networks:
      - monitor-net
    read_only: true
    security_opt:
      - no-new-privileges:true
    depends_on:
      - prometheus
      - loki
      - tempo

networks:
  monitor-net:
    driver: bridge

volumes:
  grafana_data:
  prometheus_data:
  loki_data:
  tempo_data:
