receivers:
  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu: {}
      load: {}
      memory: {}
      disk: {}
      filesystem: {}
      network: {}
      paging: {}
      processes: {}

  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: "prometheus:9090"

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    labels:
      resource:
        host.name: "${HOSTNAME}"
        service.name: "vps-monitoring"

  tempo:
    endpoint: "http://tempo:3200"
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [hostmetrics, otlp]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      exporters: [loki]
    traces:
      receivers: [otlp]
      exporters: [tempo]
